name: Run - Publisher

on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [main]
    types: [closed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      COMMIT_ID_CHOICE:
        description: 'Choose "publish-all-artifacts-in-repo" only when you want to force republishing all artifacts (e.g. after build failure). Otherwise stick with the default behavior of "publish-artifacts-in-last-commit"'
        required: true
        type: choice
        default: "publish-artifacts-in-last-commit"
        options:
          - "publish-artifacts-in-last-commit"
          - "publish-all-artifacts-in-repo"
      APIM_INSTANCE:
        description: 'Choose the APIM instance to deploy to'
        required: true
        type: choice
        options:
          - "a"
          - "b"
          - "group"
          
jobs:

# write a github action that sets the value of the APIM_INSTANCE variable based on the input or label


  set-variables:
    runs-on: ubuntu-latest
    steps:
    - name: set-variables1
      id: set-variables1
      run: |
          labels="$(gh api repos/$OWNER/$REPO_NAME/pulls/$PULL_REQUEST_NUMBER --jq '.labels.[].name')"
          
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            value="${{ github.event.inputs.APIM_INSTANCE }}"
            echo "The value in first if: $value"
          elif [[ $labels =~ ("instance-a") ]]; then
            value="a"
          elif [[ $labels =~ ("instance-b") ]]; then
            value="b"
          elif [[ $labels =~ ("instance-group") ]]; then
            value="group"
          fi
            echo "instance=$(echo $value)" >> $GITHUB_OUTPUT
      shell: bash
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
    outputs:
      instance: ${{ steps.set-variables1.outputs.instance }}
       
  get-commit:
    runs-on: ubuntu-latest
    needs: set-variables
    steps:
      # Set the COMMIT_ID env variable
      - name: Set the Commit Id
        id: commit
        run: |
          echo "::set-output name=commit_id::${{ github.sha }}"
          echo "instance=${{ needs.set-variables.outputs.instance }}" >> $GITHUB_OUTPUT
    outputs:
      commit_id: ${{ steps.commit.outputs.commit_id }}
      instance: ${{ steps.commit.outputs.instance }}

  
  #Publish without Commit ID. Publishes all artifacts that reside in the artifacts forlder
  Push-Changes-To-APIM-Dev-Without-Commit-ID:
    if: ( github.event.inputs.COMMIT_ID_CHOICE == 'publish-all-artifacts-in-repo' )
    needs: get-commit
    uses: ./.github/workflows/run-publisher-with-env.yaml
    with:
      API_MANAGEMENT_ENVIRONMENT: ${{ needs.get-commit.outputs.instance }}
      API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts # change this to the artifacts folder
    secrets: inherit

  Push-Changes-To-APIM-Prod-With-Commit-ID:
    if: (github.event.inputs.COMMIT_ID_CHOICE == 'publish-artifacts-in-last-commit' || github.event.inputs.COMMIT_ID_CHOICE == '')
    needs: [get-commit]
    uses: ./.github/workflows/run-publisher-with-env.yaml
    with:
      API_MANAGEMENT_ENVIRONMENT: ${{ needs.get-commit.outputs.instance }}
      CONFIGURATION_YAML_PATH: configuration.prod.yaml # make sure the file is available at the root
      API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts # change this to the artifacts folder
      COMMIT_ID: ${{ needs.get-commit.outputs.commit_id }}
    secrets: inherit

  Push-Changes-To-APIM-Prod-Without-Commit-ID:
    if: ( github.event.inputs.COMMIT_ID_CHOICE == 'publish-all-artifacts-in-repo' )
    needs: [get-commit, Push-Changes-To-APIM-Dev-Without-Commit-ID]
    uses: ./.github/workflows/run-publisher-with-env.yaml
    with:
      API_MANAGEMENT_ENVIRONMENT: ${{ needs.get-commit.outputs.instance }}
      CONFIGURATION_YAML_PATH: configuration.prod.yaml # make sure the file is available at the root
      API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts # change this to the artifacts folder
    secrets: inherit
