name: Run - Publisher

on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [main]
    types: [closed, labeled]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      COMMIT_ID_CHOICE:
        description: 'Choose "publish-all-artifacts-in-repo" only when you want to force republishing all artifacts (e.g. after build failure). Otherwise stick with the default behavior of "publish-artifacts-in-last-commit"'
        required: true
        type: choice
        default: "publish-artifacts-in-last-commit"
        options:
          - "publish-artifacts-in-last-commit"
          - "publish-all-artifacts-in-repo"
      APIM_INSTANCE:
        description: 'Choose the APIM instance to deploy to'
        required: true
        type: choice
        options:
          - "a"
          - "b"
          - "group"
          
jobs:

# write a github action that sets the value of the APIM_INSTANCE variable based on the input or label


  set-variables:
    runs-on: ubuntu-latest
    steps:
    - name: Get input or label value      
      id: set-variables1
      run: |
        value="a"
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          value="${{ github.event.inputs.APIM_INSTANCE }}"
          echo "The value in first if: $value"
        elif "instance-a" in github.event.pull_request.labels.*.name; then
          value="a"
          echo "The value in second if: $value"
        elif "instance-b" in github.event.pull_request.labels.*.name; then
          value="b"
          echo "The value in third if: $value"
        elif "instance-group" in github.event.pull_request.labels.*.name; then
          value="group"
          echo "The value in fourth if: $value"
        fi
          echo "The value is: $value"

          echo "instance=$(echo $value)" >> $GITHUB_OUTPUT
          echo ${{ steps.set-variables1.outputs.instance }}

    outputs:
      instance: ${{ steps.set-variables1.outputs.instance }}
  
  via-python: 
    runs-on: ubuntu-latest
    steps:
    - name: Display the path
      run: |    
        const apiminstance = "";
        if core.getInput('APIM_INSTANCE') != ""
          match core.getInput('APIM_INSTANCE')
            case "a":
              apiminstance = "a";
            case "b":
              apiminstance = "b";
            case "group":
              apiminstance = "group";
        else:
          labels = context.payload['pull_request']['labels']
          for label in labels:
            if label['name'] == 'instance-a':
              apiminstance = "a"
              break
            elif label['name'] == 'instance-b':
              apiminstance = "b"
              break
            elif label['name'] == 'instance-group':
              apiminstance = "group"
              break
        print('value is:', apiminstance)
      shell: python

       
  get-commit:
    runs-on: ubuntu-latest
    needs: set-variables
    steps:
      # Set the COMMIT_ID env variable
      - name: Set the Commit Id
        id: commit
        run: |
          echo "::set-output name=commit_id::${{ github.sha }}"
          echo "instance=${{ needs.set-variables.outputs.instance }}" >> $GITHUB_OUTPUT
    outputs:
      commit_id: ${{ steps.commit.outputs.commit_id }}
      instance: ${{ steps.commit.outputs.instance }}

  
  #Publish without Commit ID. Publishes all artifacts that reside in the artifacts forlder
  Push-Changes-To-APIM-Dev-Without-Commit-ID:
    if: ( github.event.inputs.COMMIT_ID_CHOICE == 'publish-all-artifacts-in-repo' )
    needs: get-commit
    uses: ./.github/workflows/run-publisher-with-env.yaml
    with:
      API_MANAGEMENT_ENVIRONMENT: ${{ needs.get-commit.outputs.instance }}
      API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts # change this to the artifacts folder
    secrets: inherit

  Push-Changes-To-APIM-Prod-With-Commit-ID:
    if: (github.event.inputs.COMMIT_ID_CHOICE == 'publish-artifacts-in-last-commit' || github.event.inputs.COMMIT_ID_CHOICE == '')
    needs: [get-commit]
    uses: ./.github/workflows/run-publisher-with-env.yaml
    with:
      API_MANAGEMENT_ENVIRONMENT: ${{ needs.get-commit.outputs.instance }}
      CONFIGURATION_YAML_PATH: configuration.prod.yaml # make sure the file is available at the root
      API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts # change this to the artifacts folder
      COMMIT_ID: ${{ needs.get-commit.outputs.commit_id }}
    secrets: inherit

  Push-Changes-To-APIM-Prod-Without-Commit-ID:
    if: ( github.event.inputs.COMMIT_ID_CHOICE == 'publish-all-artifacts-in-repo' )
    needs: [get-commit, Push-Changes-To-APIM-Dev-Without-Commit-ID]
    uses: ./.github/workflows/run-publisher-with-env.yaml
    with:
      API_MANAGEMENT_ENVIRONMENT: ${{ needs.get-commit.outputs.instance }}
      CONFIGURATION_YAML_PATH: configuration.prod.yaml # make sure the file is available at the root
      API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts # change this to the artifacts folder
    secrets: inherit
